### ISSUE TITLE
[Feat] Scrollable한 List 구현

### ISSUE THREAD

**Issue by alpaka99** [alpaka99/LZTunes#10]
# iTunes API + RxSwift  🎶📱

## 작업 설명 🛠️
- #8 에서 받아온 데이터를 사용자에게 전달해주기 위한 UI 작업을 진행합니다.

## Todos ✅
- [ ] 현재의 TableView의 Cell의 UI 구현
- [ ] 클릭했을때 넘어가는 화면의 UI 구현
- [ ] 데이터 전달 흐름 확인하기
