### ISSUE TITLE
[Feat] iTunes API 통신하기

### ISSUE THREAD

**Issue by alpaka99** [alpaka99/LZTunes#6]
# iTunes API + RxSwift  🎶📱

## 작업 설명 🛠️
- iTunes API와 통신을 구현합니다

## Todos ✅

- [x] NetworkManager 구현 (싱글톤 패턴)
- [x] Router Pattern을 통한 request 구현
- [x] Response 확인 및  알맞은 형태로 디코딩
